#%RAML 1.0
title: Users Api
version: 1.0.development
baseUri: http://prolearn.com/api
securitySchemes:
  oauth_2_0:
    description: |
      This API supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid OAuth 2 access token. Do not use with the "access_token" query
             string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token. Do not use together with the "Authorization"
             header
          type: string
      responses:
        401:
          description: |
            Bad or expired token. This can happen if the user or the API revoked or expired an
            access token. To fix, you should re-authenticate the user.
        403:
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately,
            re-authenticating the user won't help here.
    settings:
      authorizationUri: https://localhost:8081/external/authorize
      accessTokenUri: https://localhost:8081/external/access_token
      authorizationGrants: [authorization_code, password, client_credentials, implicit]
/users:
  get:
    description: Retrieve a list of all users
    responses:
      200:
        body:
          application/json:
            example: !include users-example.json
  /{id}:
    get:
      description: Get information about a particular user
      responses:
        200:
          body:     
            application/json:
              example: !include user-example.json
                  
                  